inputPath: $HOME/statementer/input
outputPath: $HOME/statementer/output
workPath: /tmp/statementer
sumExt: sum
inputExt: pdf
debug: false
ignorePaths:
    -   "$HOME/stuff"
statements:
    -   name: Credit Card 1
        account: 123123123123123123
        processor: chase-credit-card
    -   name: Personal Checking
        account: 123123123123
        processor: chase-checking