inputPath: $HOME/Dropbox/docsorter/input
outputPath: $HOME/Dropbox/docsorter/output
workPath: /tmp/docksorter
sumExt: sum
inputExt: pdf
debug: false
ignorePaths:
    -   "$HOME/Dropbox/.dropbox"
statements:
    -   name: Amazon Card
        account: 4640182104187285
        processor: chase-credit-card
    -   name: Joint Account
        account: 633156029
        processor: chase-checking