version: "3"
services:
    imagemagick:
        image: boundedinfinity:imagemagick
        user: $UID:$GID
        build:
            context: .
            dockerfile: Dockerfile.imagemagick
        volumes:
            - ${WORK_DIR}:/work
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - /home/$USER:/home/$USER
        environment:
            HOST_UID: $UID
            HOST_GID: $GID
    tesseract:
        image: boundedinfinity:tesseract
        user: $UID:$GID
        build:
            context: .
            dockerfile: Dockerfile.tesseract
        volumes:
            - ${WORK_DIR}:/work
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - /home/$USER:/home/$USER
        environment:
            HOST_UID: $UID
            HOST_GID: $GID

